### PR TITLE
Fix install button position

### PR DESCRIPTION
**Pull request by RReverser**
Add `position: relative` to the parent `div` that owns the scrollbar, so that Install button positions itself relative to it and not to the whole document.

Fixes a bug where button would get rendered on top of a scrollbar.

Before:

image

After:

image

### CODE REVIEW

**Comment by surma** [comment]
I think you snuck in a commit there that’s not supposed to be in here

**Comment by RReverser** [comment]
Ah, it's just an unrebased branch.

**Comment by RReverser** [comment]
Did the "merge branch" thingy, now with Squash & Merge the extra commit shouldn't matter :)

**Comment by RReverser** [comment]
Ping.

**Review by nucliweb — APPROVED** [review]

**Review by surma — APPROVED** [review]

**Pull request merged**
