### PR TITLE
added snack bar inside noscript element

### LINKED ISSUE #593: When JS is disabled no message is displayed
**Describe the bug**
When opening the page in any browser and disabling JS, the page does not react. It just displays everything like normal but does not respond to any clicks (obviously).

**To Reproduce**
1. Go to squoosh
2. Disable JS
3. Reload page

**Expected behavior**
Display a message or screen that JS is needed to use Squoosh.

**Version:**
 - OS w/ version: any
 - Browser w/ version any
 - Node version: n/a
 - npm version:  n/a

### PR DESCRIPTION
**Pull request by tsukinoko-kun**
Display a snackbar when javascript is disabled.
Snackbar button reloads the page (as an anchor tag).

Desktop:
Screenshot Desktop

Mobile:
Screenshot Mobile

closes #593

### CODE REVIEW

**Comment by tsukinoko-kun** [comment]
If there is a better way to provide the styles, let me know.

**Comment by surma** [comment]
That’s actually a really cool idea. I feel like the wording could be a bit more actionable, like “This site requires JavaScript” or something along those lines.

**Comment by tsukinoko-kun** [comment]
@surma
> That’s actually a really cool idea. I feel like the wording could be a bit more actionable, like “This site requires JavaScript” or something along those lines.

The message now says: "Initialization error: This site requires JavaScript, which is disabled in your browser."

**Comment by harsh26shah03** [comment]
Better, but we should keep user away from jargons, "Please enable Javascript to use Squoosh" will be a better choice of words @surma ?

**Review by argyleink — APPROVED** [review]
lgtm 👍🏻 
<br>

> If there is a better way to provide the styles, let me know.

Seems fine to me, I didn't find any double loading happening or anything concerning.

**Comment by tsukinoko-kun** [comment]
Can this be merged, or should I change something?

**Pull request merged**
