### PR TITLE
Don’t use instantiateStreaming for rotate wasm module

### LINKED ISSUE #493: Rotation change doesn't work on Safari.
Since [WebAssembly.instantiateStreaming](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming) method has no support on Safari, changing the rotation of an image on Safari causes an error being thrown.

**Steps to reproduce the behavior:**
1. Open the app in Safari browser.
2. Select an image.
3. Click rotation-change button.

**Versions:**
 - OS version: MacOS 10.14.3
 - Browser version: Safari 12.0.3
 - Node version: 10.15.1
 - npm version: 6.4.1

**Screen-shot:**

screen shot 2019-03-04 at 16 13 05

### PR DESCRIPTION
**Pull request by surma**
Fixes #493 

(H/T @alisaitbilgi)

### CODE REVIEW

**Comment by alisaitbilgi** [comment]
I was thinking to try something like that and not sure to have a performance penalty by feature detecting **instantiateStreaming**:

```
const getInstancePromise = async () => {
  const response = await fetch(wasmUrl);
  const buffer = await response.arrayBuffer();
  const module = await WebAssembly.compile(buffer);

  return WebAssembly.instantiate(module);
};

const instancePromise = ('instantiateStreaming' in WebAssembly)
  ? (WebAssembly as any).instantiateStreaming(fetch(wasmUrl))
  : getInstancePromise();
```

**Comment by surma** [comment]
As I say in the comment in the code, I don’t think it’s worth shipping the detection code considering we are loading a 500B wasm module here.

**Comment by alisaitbilgi** [comment]
hoo, cool I thought it was 500MB :D

**Comment by surma** [comment]
That would _not_ have made it to production. Ever. 😂

**Pull request merged**
