### PR TITLE
Feat : added hover animation to sample data

### LINKED ISSUE #871: [new homepage] samples images need focus/hover styles

### LINKED ISSUE #1192: Wrong units on the main website
**Describe the bug**
image

I doubt You wanted to show the file sizes in milibits (mb). After checking the size of these assets I confirmed the proper unit would be Megabyte (MB)
Also, the last file's size does not even have a unit - it's just 13k (k what?) - and the size is actually 10.7 kB, not 13.

Taking this a step further I would recommend using [IEC prefixes](https://en.wikipedia.org/wiki/Binary_prefix#mebi) - eg. Mebibytes - instead of the SI ones.

### PR DESCRIPTION
**Pull request by harsh26shah03**
Sample data:  on hover added minimal scale effect 

see,

https://user-images.githubusercontent.com/48324810/229501550-49cae370-c5a5-4bdd-8241-a69a0c8ef403.mov

Closed #871

### CODE REVIEW

**Review by argyleink — CHANGES_REQUESTED** [review]
half of this certainly pacifies the hover feature, but the other half feels like a suggestion for a separate PR. Can you break out the file size suffix suggestion into a separate PR please?

**Comment by harsh26shah03** [comment]
Sure, you will have a PR raised and file size in this PR will be undone.

**Comment by harsh26shah03** [comment]
@argyleink ready for review

**Review by argyleink — APPROVED** [review]
ty! works as advertised <3

**Pull request merged**
