### PR TITLE
Adds Download support. Fixes #47

### LINKED ISSUE #47: Download image link
For each compressed image, we need a button that downloads the compressed image.

### PR DESCRIPTION
**Pull request by PaulKinlan**
New version of downloadUrl that is a lot simpler now.

+ For images that are not encoded by Identity encoder, will create a download url
+ Uses data in the encoder to get file type (note: adds '' to identity encoder)
+ Hoists some of the logic in the updateImage function

### CODE REVIEW

**Comment by developit** [comment]
I started to resolve the conflict but it's a tad thick, probably better to leave that for either of you.

**Comment by jakearchibald** [comment]
I'll do it

**Comment by PaulKinlan** [comment]
/me squints.... I'm presuming I missed a large refactor that landed on master...

**Comment by PaulKinlan** [comment]
Looking at this, it looks pretty simple to fix. However, I will be on a flight and it might not have wifi.

**Comment by jakearchibald** [comment]
I've sneaked a fix for a race condition in here. Technically it shouldn't be part of this PR, but feels like it'll cause the least amount of merge conflicts here.

**Comment by jakearchibald** [comment]
This is ready for fresh review.

**Comment by jakearchibald** [comment]
I could have sworn I merged this. Will do it manually.

**Pull request closed without merging**
