### PR TITLE
Add firebase hosting

### PR DESCRIPTION
**Pull request by developit**

### CODE REVIEW

**Comment by jakearchibald** [comment]
I'm ok with this PR but we shouldn't consider it a done deal. We should also look at serving straight from a storage bucket.

I'm curious about:

* Differences in cost.
* Differences in using a custom domain.
* Control over response headers, and the ease of setting them (the current headers are bad).

We also need to make sure this is set up internally so billing goes to the right place.

**Comment by developit** [comment]
Definitely just an interim thing. I'd assumed we'd get this set up somewhere more official soon, just wanted a place with proper h2 + http redirects so lighthouse was happy.

**Comment by surma** [comment]
My 2c: I like FB Hosting as a target. You have full control over headers (more so than GCS) and it’s pretty frictionless. But I’ll go with whatever.

**Comment by developit** [comment]
That was the other killer feature here. We could grab the `firebase.json` Link header generation bit from preact-cli and get automatic h/2 push.

**Comment by surma** [comment]
Gonna be honest: I don’t wanna deal with h2 push and all its problems. I’d rather not bring it into this project.

**Comment by developit** [comment]
Even so, the Link header for preload can still provide an advantage over preloading via meta tags, right?

**Comment by surma** [comment]
Sorry, I kinda side-tracked this PR with my comment — my comment does not veto this PR at all.

(And yes, I think being able to control HTTP Link headers can be valuable.)

**Comment by surma** [comment]
@developit Please rebase & fix once you are back at work :)

**Comment by surma** [comment]
🎉

**Pull request merged**
