### PR TITLE
Filedrop wc

### PR DESCRIPTION
**Pull request by jakearchibald**
Reopening https://github.com/GoogleChromeLabs/squoosh/pull/200

### CODE REVIEW

**Comment by jakearchibald** [comment]
I'm happy to fix the merge here. @PaulKinlan is the side project in a state you're happy with?

**Comment by PaulKinlan** [comment]
Not sure what the issue is here. The WC is included from the external
project already... No?

**Comment by jakearchibald** [comment]
I don't think it was merged. I could be making shit up though.

**Comment by PaulKinlan** [comment]
Ok. I'll check monday.

**Comment by jakearchibald** [comment]
@PaulKinlan this looks good to me. I've rebased it against the newer stuff I've been doing. I can't approve this PR because I created it, but I'll merge it once the other stuff has been merged.

**Pull request merged**
