### PR TITLE
Switch from napa to curl

### PR DESCRIPTION
**Pull request by RReverser**
Instead of using 127 deps brought by napa just to download the one dependency we actually care about, just use curl & tar directly from Makefile.

### CODE REVIEW

**Comment by jakearchibald** [comment]
Would this impact Windows compatibility?

**Comment by RReverser** [comment]
We already build inside Docker, and codecs already use Make, so no :)

**Comment by jakearchibald** [comment]
Ah cool, I thought the napa part currently ran outside of docker.

**Comment by RReverser** [comment]
Ah yeah it did, but is it useful for user without ability to build?

**Comment by jakearchibald** [comment]
Nope, makes sense to move that all into dockerland

**Review by surma — APPROVED** [review]

**Pull request merged**
