### PR TITLE
 Removes the file-drop custom element and replace with WC

### PR DESCRIPTION
**Pull request by PaulKinlan**
+ Removes the custom element from the project
+ Replaces it with the externally maintined custom element

### CODE REVIEW

**Comment by PaulKinlan** [comment]
@jakearchibald did your appsplit branch land on main?

**Comment by jakearchibald** [comment]
Not yet, it's waiting on review.

**Comment by jakearchibald** [comment]
https://github.com/GoogleChromeLabs/squoosh/pull/197

**Comment by jakearchibald** [comment]
Ugh, this is another auto-closed one

**Comment by PaulKinlan** [comment]
I thought this was already merged in?

I can take a stab at it again on Monday. Will only take minutes.

**Pull request closed without merging**
