### PR TITLE
Feat : Showing source file name

### PR DESCRIPTION
**Pull request by harsh26shah03**
There will be file name shown in pink theme
at top right corner in desktop mode

added a file title at the top right corner

Screenshot 2023-04-02 at 10 07 25 PM

I hope it looks good and it won't be available for mobileview

### CODE REVIEW

**Comment by harsh26shah03** [comment]
Closes #244

**Comment by argyleink** [comment]
I feel like #1353 is sufficient for resolving #244.
other's thoughts?

**Comment by harsh26shah03** [comment]
@argyleink I felt same as well but created this anyway to explore options

**Comment by surma** [comment]
Yeah I’d prefer #1353.

Amazing stuff, @harsh26shah03!

**Comment by harsh26shah03** [comment]
thanks @surma, also check my new feature #1359

**Pull request closed without merging**
