### PR TITLE
Main ui

### PR DESCRIPTION
**Pull request by jakearchibald**
Ready to merge.

### CODE REVIEW

**Comment by jakearchibald** [comment]
@mustafa-x Ignore everything to do with the options panels for now. They're in progress.

**Comment by jakearchibald** [comment]
@mustafa-x https://deploy-preview-214--squoosh.netlify.com/

This PR should reflect the final design, except anything in the option panels which I'll do separately.

* [ ] Add dotted border on intro screen.

Anything else?

**Comment by mustafa-x** [comment]
tools tips :) 

Otherwise looks good to me, the labels of the drop boxes are off by a pixel but otherwise LGTM

screen shot 2018-10-17 at 3 49 26 pm

**Comment by jakearchibald** [comment]
fwiw, I'm going to leave the intro screen changes until I do the service worker options.

**Comment by mustafa-x** [comment]
sounds good to me.

**Pull request merged**
