### PR TITLE
Remove origin trial header

### LINKED ISSUE #1139: Remove WebAssembly SIMD origin trial token
Since WebAssembly SIMD origin trial ended, it is no longer useful to have this token in https://squoosh.app.

image
*DevTools Screenshots*

Note that WebAssembly SIMD has shipped in Chrome 91 according to https://www.chromestatus.com/feature/6533147810332672

### PR DESCRIPTION
**Pull request by beaufortfrancois**
FIX https://github.com/GoogleChromeLabs/squoosh/issues/1139

### CODE REVIEW

**Comment by jakearchibald** [comment]
Is SIMD properly released now?

**Comment by beaufortfrancois** [comment]
That is my understanding: https://github.com/GoogleChromeLabs/squoosh/issues/1139#issue-985094092

**Comment by beaufortfrancois** [comment]
See https://github.com/WebAssembly/meetings/blob/main/simd/2021/SIMD-08-06.md as well

**Review by RReverser — APPROVED** [review]
Makes sense, thanks.

**Pull request merged**
