### PR TITLE
Simplify code contributions, reviews and automate dev setup with a single click

### PR DESCRIPTION
**Pull request by nisarhassan12**
Hey there, :wave:

this PR simplifies code contributions by fully automating the dev setup with Gitpod (a free online VS Code-like IDE). With a single click, it'll launch a workspace and automatically:

- clone the squoosh repo.
- install the dependencies.
- run  `yarn serve`.

So that anyone interested in contributing can start straight away.

You can give it a try on my fork of the repo via the following link: 

https://gitpod.io/#https://github.com/nisarhassan12/squoosh

image

### CODE REVIEW

**Comment by nisarhassan12** [comment]
Rebased on top of the latest master.

**Comment by nisarhassan12** [comment]
Rebased on top of latest master @surma @jakearchibald @kosamari

**Comment by surma** [comment]
While this PR was closed by accident, I am not going to re-open this one. I appreciate where you are coming from, but we want to minimize external tooling.

**Comment by zy6p** [comment]
@nisarhassan12 Gitpod is a great project. But when I use gitpod chrome extension to open this repo, it encounters an error like this:

image

> Request createWorkspace failed with message: 13 INTERNAL: cannot resolve workspace image: hostname required

> Unknown Error: { "code": -32603 }

**Pull request closed without merging**
