### PR TITLE
Fix build on Windows

### LINKED ISSUE #282: Build fails on Windows 10
Seems to be an issue with the webpack, any guidance?

$ npm run build

> squoosh@1.0.2 build C:\Squoosh\squoosh
> webpack -p

   76 modules

ERROR in ./src/codecs/processor-worker.ts (./node_modules/worker-plugin/dist/loader.js?{"name":"processor-worker"}!./src/codecs/processor-worker.ts)
Module build failed (from ./node_modules/worker-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in 'C:\Squoosh\squoosh\codecs\imagequant'
    at factory.create (C:\Squoosh\squoosh\node_modules\webpack\lib\Compilation.js:797:10)
    at factory (C:\Squoosh\squoosh\node_modules\webpack\lib\NormalModuleFactory.js:397:22)
    at resolver (C:\Squoosh\squoosh\node_modules\webpack\lib\NormalModuleFactory.js:130:21)
    at asyncLib.parallel (C:\Squoosh\squoosh\node_modules\webpack\lib\NormalModuleFactory.js:224:22)
    at C:\Squoosh\squoosh\node_modules\neo-async\async.js:2817:7
    at C:\Squoosh\squoosh\node_modules\neo-async\async.js:6783:13
    at normalResolver.resolve (C:\Squoosh\squoosh\node_modules\webpack\lib\NormalModuleFactory.js:214:25)
    at doResolve (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:184:12)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn41 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:381:1)
    at resolver.doResolve (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\ModuleKindPlugin.js:23:37)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at args (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\forEachBail.js:30:14)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn42 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:393:1)
    at hook.callAsync (C:\Squoosh\squoosh\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Squoosh\squoosh\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)

### PR DESCRIPTION
**Pull request by developit**
Fixes #282.

### CODE REVIEW

**Comment by pewstiepoll** [comment]
Using this RegExp: `/[\/\\]codecs[\/\\]/` works for me on Windows 10

**Comment by surma** [comment]
@pewstiepoll `path.sep` is definitely more robust.

**Comment by DevonJSmith** [comment]
@surma @developit  issue #282 has not been resolved for me with this

I get the following output when running `npm run build`:

```
D:\Projects\squoosh\node_modules\webpack-cli\bin\cli.js:244
                                throw
err;
                                ^

SyntaxError: Invalid regular expression: /\codecs\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at module.exports (D:\Projects\squoosh\webpack.config.js:174:9)
    at handleFunction (D:\Projects\squoosh\node_modules\webpack-cli\bin\prepareOptions.js:23:13)
    at prepareOptions (D:\Projects\squoosh\node_modules\webpack-cli\bin\prepareOptions.js:9:5)
    at requireConfig (D:\Projects\squoosh\node_modules\webpack-cli\bin\convert-argv.js:136:14)
    at D:\Projects\squoosh\node_modules\webpack-cli\bin\convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (D:\Projects\squoosh\node_modules\webpack-cli\bin\convert-argv.js:140:15)
    at yargs.parse (D:\Projects\squoosh\node_modules\webpack-cli\bin\cli.js:241:39)
    at Object.parse (D:\Projects\squoosh\node_modules\webpack-cli\node_modules\yargs\yargs.js:563:18)
    at D:\Projects\squoosh\node_modules\webpack-cli\bin\cli.js:219:8
    at Object.<anonymous> (D:\Projects\squoosh\node_modules\webpack-cli\bin\cli.js:538:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\Projects\squoosh\node_modules\webpack\bin\webpack.js:155:2)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

Indeed, when running these commands in `node` locally in a CMD terminal, I get the same output:
```javascript
var path = require('path');
new RegExp(`${path.sep}codecs${path.sep}`);
SyntaxError: Invalid regular expression: /\codecs\/: \ at end of pattern
```
Seems like the `\` might need to be escaped in the RegEx but I've tried doubling up the separators without avail.

Also, doesn't this fix need to be done to lines 149 and 153 ? 
```javascript
 test: /\/codecs\/.*\.js$/,
```
```javascript
 test: /\/codecs\/.*\.wasm$/,
```

**Comment by ravingdev** [comment]
> @surma @developit issue #282 has not been resolved for me with this
> 
> I get the following output when running `npm run build`:
> 
> ```
> D:\Projects\squoosh\node_modules\webpack-cli\bin\cli.js:244
>                                 throw
> err;
>                                 ^
> 
> SyntaxError: Invalid regular expression: /\codecs\/: \ at end of pattern
>     at new RegExp (<anonymous>)
>     at module.exports (D:\Projects\squoosh\webpack.config.js:174:9)
>     at handleFunction (D:\Projects\squoosh\node_modules\webpack-cli\bin\prepareOptions.js:23:13)
>     at prepareOptions (D:\Projects\squoosh\node_modules\webpack-cli\bin\prepareOptions.js:9:5)
>     at requireConfig (D:\Projects\squoosh\node_modules\webpack-cli\bin\convert-argv.js:136:14)
>     at D:\Projects\squoosh\node_modules\webpack-cli\bin\convert-argv.js:142:17
>     at Array.forEach (<anonymous>)
>     at module.exports (D:\Projects\squoosh\node_modules\webpack-cli\bin\convert-argv.js:140:15)
>     at yargs.parse (D:\Projects\squoosh\node_modules\webpack-cli\bin\cli.js:241:39)
>     at Object.parse (D:\Projects\squoosh\node_modules\webpack-cli\node_modules\yargs\yargs.js:563:18)
>     at D:\Projects\squoosh\node_modules\webpack-cli\bin\cli.js:219:8
>     at Object.<anonymous> (D:\Projects\squoosh\node_modules\webpack-cli\bin\cli.js:538:3)
>     at Module._compile (internal/modules/cjs/loader.js:688:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)    at Module.load (internal/modules/cjs/loader.js:598:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
>     at Module.require (internal/modules/cjs/loader.js:636:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (D:\Projects\squoosh\node_modules\webpack\bin\webpack.js:155:2)
>     at Module._compile (internal/modules/cjs/loader.js:688:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)    at Module.load (internal/modules/cjs/loader.js:598:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
>     at startup (internal/bootstrap/node.js:285:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
> ```
> Indeed, when running these commands in `node` locally in a CMD terminal, I get the same output:
> 
> ```js
> var path = require('path');
> new RegExp(`${path.sep}codecs${path.sep}`);
> SyntaxError: Invalid regular expression: /\codecs\/: \ at end of pattern
> ```
> 
> Seems like the `\` might need to be escaped in the RegEx but I've tried doubling up the separators without avail.
> 
> Also, doesn't this fix need to be done to lines 149 and 153 ?
> 
> ```js
>  test: /\/codecs\/.*\.js$/,
> ```
> 
> ```js
>  test: /\/codecs\/.*\.wasm$/,
> ```
i am also facing same issue
i am using windows 10
i tried with new RegExp(`${path.sep}${path.sep}codecs${path.sep}${path.sep}`); the regex is creating succesfully .

**Pull request merged**
