### PR TITLE
[cli] Handle all color types in png decoder

### LINKED ISSUE #971: Squoosh CLI incorrectly handles grayscale PNGs
**Before you start**
Please take a look at the [FAQ](https://github.com/GoogleChromeLabs/squoosh/wiki/FAQ) as well as the already opened issues! If nothing fits your problem, go ahead and fill out the following template:

**Describe the bug**
Squoosh CLI doubles the image and changed the hue for grayscale PNGs:

It can be reproduced with both WebP and OxiPNG, but it works expectedly in the web app. 

**To Reproduce**
1. Download https://imgur.com/wgqaUdn (or https://i.imgur.com/eTgdpzy.png)
2. Run `squoosh-cli --webp auto image.png`
3. See bug

**Expected behavior**
It should not change the image content.

**Version:**
 - OS w/ version: macOS 11.2.2
 - Browser w/ version: n/a
 - Node version: v14.16.0
 - npm version: 6.14.11

**Is your issue related to the quality of image compression?**
Please attach original and output images (you can drag & drop to attach). 
- Original image 

test-2

- Output image from Squoosh

test-2-output-oxipng

**Additional context, screenshots, screencasts**

Here's a full screenshot of commands I ran:

CleanShot 2021-03-11 at 03 00 39@2x

### PR DESCRIPTION
**Pull request by RReverser**
Add conversions for all color types in PNG decoder used in CLI. (While at it, also made few minor cleanups.)

Fixes #971.

### CODE REVIEW

**Review by surma — APPROVED** [review]

**Comment by surma** [comment]
Nice, thank you!

**Comment by RReverser** [comment]
@surma Can you take care of the npm release?

**Comment by shuding** [comment]
Hey folks, thank you so much for fixing this! Do we have a timeline for the next release? @surma

**Comment by ezioda004** [comment]
Hey @surma, any timeline for this release?

**Pull request merged**
