### PR TITLE
Update JPEG XL to use github repos.

### PR DESCRIPTION
**Pull request by veluca93**
Also update to latest main.

### CODE REVIEW

**Review by jakearchibald — APPROVED** [review]

**Comment by RReverser** [comment]
I'd like to merge this after #1027 to reduce conflicts.

**Comment by jakearchibald** [comment]
Ok, no problem

**Comment by RReverser** [comment]
@veluca93 Hi, can you please rebase on latest `dev` and clean-rebuild (`rm -rf node_modules && npm run build`)?

**Comment by veluca93** [comment]
Done!

**Comment by RReverser** [comment]
Ha, that was quick. A bit surprising that changes are practically non-existent, but I guess that's a good sign :)

**Comment by surma** [comment]
> A bit surprising that changes are practically non-existent

Is that surprising considering all that changed is most likely the repo URL?

On that note: I don’t see a new repo URL in the diff (or any changes to the `Makefile` for that matter).

**Comment by veluca93** [comment]
Probably my fault :) I'll figure it out tomorrow...

**Comment by RReverser** [comment]
> Is that surprising considering all that changed is most likely the repo URL?

I guess not, I just assumed there were a bunch of upstream changes meanwhile as well.

**Comment by surma** [comment]
@veluca93 friendly ping on this one :D (Also needs a rebase by now)

**Comment by veluca93** [comment]
> @veluca93 friendly ping on this one :D (Also needs a rebase by now)

Hah, sorry, I had entirely forgotten. PTAL :)

**Pull request merged**
