### PR TITLE
progressively enhance to `oklch`

### PR DESCRIPTION
**Pull request by argyleink**
if display is HD and browser can parse `oklch`, go ahead and make the blue and pink hotter.

### CODE REVIEW

**Comment by argyleink** [comment]
found a Chrome bug while making this, wait to merge until the bug is resolved 👍🏻

**Comment by jakearchibald** [comment]
Ohh what's the bug?

**Comment by argyleink** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1430225

**Comment by jakearchibald** [comment]
Ohh good catch

**Comment by argyleink** [comment]
bug is resolved in stable; PR is g2g

**Pull request merged**
