### PR TITLE
Image height and width fix. 

### PR DESCRIPTION
**Pull request by velusgautam**
rawImage is a Uint8ClampedArray and doesn't have width and height property.

### CODE REVIEW

**Comment by velusgautam** [comment]
@surma can you have a look

**Review by jakearchibald — APPROVED** [review]
Hah coincidentally I ran into this issue yesterday! You might be interested in the rollup-build branch where I've been going through this stuff.

**Comment by velusgautam** [comment]
@jakearchibald Why pixelated image rendering css for imagequant example only. Just curious
  canvas {
    image-rendering: pixelated;
  }

**Comment by jakearchibald** [comment]
Just to make it easier to see the colour reduction

**Pull request merged**
